[workspace]
resolver = "2"

members = [
    "apps/robot",
    "apps/generator",
    "crates/shared",
    "crates/pathfinding",
    "crates/slam",
]

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
dotenvy = "0.15"
rand = "0.10.1"
serde_json = "1"
shared = { path = "crates/shared" }

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["arbi"]
description = "Cave Robot — a drone that autonomously navigates randomly generated cave systems using LIDAR, SLAM, and Seeded Cellular Automata with Region Connection."
